Dev
December11/iOSLearning pull request #1
Opened 2022-06-19 22:16 UTC by December11

2022-06-20 19:00 UTC, evgeniyCache requested changes

2022-06-21 06:43 UTC, December11 commented on Task00.playground/Sources/Models/DataSource/BeautifulDataSource.swift
> +final public class BeautifulDataSource: DataSourceReadable {
Это исключительно для того, чтобы можно было вызвать класс в плейграунде. Кажется по-другому там никак. Плейграунд вроде все свои source считает отдельным модулем... При попытке инициализировать ругается что модификатор доступа internal) 

Я подумала что важно чтобы вызывался refreshScreenItems() из того же плейграунда.. А так можно убрать паблик у классов)

2022-06-21 09:30 UTC, evgeniyCache commented on Task00.playground/Sources/Models/DataSource/BeautifulDataSource.swift
> +final public class BeautifulDataSource: DataSourceReadable {
не, если там без internal нельзя, то забей и оставь)

2022-06-21 19:59 UTC, December11 commented on Task00.playground/Sources/Protocols/DataSourceReadable.swift
> +    init()
А почему он тут не нужен? из-за того что никаких требований к аргументам у него нет? типа, требуем тупо возможность заинициализировать объект и это выглядит слишком абстрактным и оттого бесполезным?

2022-06-21 20:44 UTC, December11 commented on Task00.playground/Sources/Protocols/DecodableModel.swift
> +public protocol DecodableModel {
Немного запуталась тут с неймингами. ViewModelType кажется хорошим названием для этого перечисления, 
а вот это о чем тогда?
> Название должно как-то отражать, что это именно данные для настройки `View -> ViewModel/Configuration`)

2022-06-21 22:52 UTC, December11 commented on Task00.playground/Sources/Models/DataSource/BeautifulDataSource.swift
> +            if index % 2 != 0 {
а тут если делать enumerated() и reduce и т.п. ведь будет двойной прогон одного и того же массива, да? сначала прогнали - создали кортежи индекс-значение, а потом reduce еще раз прогнал и, например, добавил сепаратор. 

можно по идее просто reduce делать, а потом в конце удалить сепаратор последний. Если были элементы в массиве, конечно

2022-06-22 09:05 UTC, December11 commented on Task00.playground/Sources/Protocols/DecodableModel.swift
> +public protocol DecodableModel {
а, я затупила, тут наверно имеется в виду что в проекте, в папке ViewModel надо создать подпапку) так?)

2022-07-12 15:59 UTC, evgeniyCache approved these changes

2022-07-12 15:59 UTC, evgeniyCache commented on Task00.playground/Sources/Extensions/CGFloat.swift
> +    var tenPercents: CGFloat {
делать расширение на весь тип излишне (тк десять процентов нам явно понадобится в очень редких кейсах (но в рамках ДЗ - ок)

2022-07-12 15:59 UTC, evgeniyCache commented on Task00.playground/Sources/Models/DataSource/BeautifulDataSource.swift
> +                header: response.header ?? "",
не помню, что мы решили тогда, но мы обсуждали, что дефолтные строчки, когда значение не пришло - не ок, потому на будущее так лучше не делать)

2022-07-12 15:59 UTC, evgeniyCache commented on Task00.playground/Sources/Models/DataSource/BeautifulDataSource.swift
> +    private func getSeparator(of startIndex: Int) -> ViewModelType {
create/make, но никак не get

2022-07-12 15:59 UTC, evgeniyCache commented on Task00.playground/Sources/Models/DataSource/BeautifulDataSource.swift
> +            _ = indicies.map { index in
что-то непонятное, зачем мы делаем _ =, то есть метод с 66ой по 69ую строчку выполняется впустую, ведь мы это никуда не сохраняем

если надо просто пройтись, то использую forEacth

2022-07-12 15:59 UTC, evgeniyCache commented on Task00.playground/Sources/Protocols/DataSourceProtocol.swift
> +    static func makeScreenItems(from responseData: [NewsDataResponse]) -> [ViewModelType]
static func должны быть выше остальных

static - nested types - (open, public, internal, private)  vars и (open, public, internal, private) methods

2022-07-12 15:59 UTC, evgeniyCache commented on Task00.playground/Sources/Models/ViewModel/Configurate/ViewModelTypes.swift
> +            case "detail": self = .detail(title, description.joined(separator: "\n"))
надо написать под case detail, а то выглядит странно (неуверен, что по кодстайлу Свифта)

2022-07-13 07:19 UTC, December11 commented on Task00.playground/Sources/Models/DataSource/BeautifulDataSource.swift
> +                header: response.header ?? "",
поправила тут)

2022-07-13 07:21 UTC, merged